### ISSUE TITLE
Game.GetMapInfo() returns incorrect values

### ISSUE THREAD

**Issue by TideSofDarK** [ModDota/BugTracker#42] opened 2016-12-16 02:58 UTC
Game.GetMapInfo().map_name now appears to be able to return the name of a seemingly random DOTAScenePanel with map value set, same DOTAScenePanel is used in Game.GetMapInfo().map_display_name

**Comment by SinZ163** [comment] 2016-12-28 01:08
This also affects the Loading screen / Game Setup sidebar menu, which isn't powered by javascript so the issue is deeper.

If you look in console too, you see the game announcing all the game state changes relative to this incorrect map name too.

**Comment by SinZ163** [comment] 2016-12-28 04:18
This bug also affects client side lua.

**Comment by DoctorGester** [comment] 2017-01-27 01:13
Fixed in Dark Moon update

**Closed by DoctorGester** 2017-01-27 01:13 UTC
Labels: bug, Confirmed, Lua API, Panorama
