### ISSUE TITLE
Add local storage in Panorama

### ISSUE THREAD

**Issue by RobinCodeX** [ModDota/BugTracker#25] opened 2016-11-23 22:25 UTC
This feature is like the player's local archives, which is very important for any game, so that players can make their own settings, rather than starting the game everyone is the same as the initial settings.

Priority: High

**Comment by SinZ163** [comment] 2016-11-24 03:56
Duplicate of #22

**Comment by Perryvw** [comment] 2016-11-24 15:18
This is not a duplicate, this is local storage, #22 is server storage.

**Comment by SinZ163** [comment] 2016-11-24 22:42
I don't see this happening, as Scaleform had / used to have local filesystem access, but panorama doesn't have it. So its either an oversight (thats been there for a long time), or it was intentionally not added, like how they removed ways of emulating clicks from panorama when they put it in dota.

**Comment by darklordabc** [comment] 2016-11-25 00:03
I'm not sure why Panorama is in this title. OP didn't specify panorama.

**Comment by SinZ163** [comment] 2016-11-25 00:11
He gave an example of $.cookie("key", "value") earlier

**Comment by darklordabc** [comment] 2016-11-25 00:18
Okay maybe that's what he was thinking about, but the feature request is really only about having local storage, panorama or not, there could be games that want local storage that don't use panorama.

**Comment by DoctorGester** [comment] 2016-11-25 00:55
Makes the most sense in panorama since it's player-local.

**Comment by darklordabc** [comment] 2016-11-25 00:59
@RobinCodeX do you think it should be only for panorama, or just a general purpose cookie system?

**Comment by SinZ163** [comment] 2016-11-25 07:30
I looked back through the old Scaleform API. We had explicit functions to read and write KV files to disk provided by Valves API endpoints.

**Comment by RobinCodeX** [comment] 2016-11-25 10:48
@darklordabc I think a general purpose cookie system is better.

**Comment by SinZ163** [comment] 2016-11-25 12:28
Within a day or three I should have a working library that does exactly this, with API endpoints for both panorama and lua

**Comment by SinZ163** [comment] 2016-11-26 07:43
And within 24 hours, a working library to do this is available in [ModDotaLib](/ModDota/ModDotaLib) with both Lua and Panorama API endpoints.

**Comment by RobinCodeX** [comment] 2016-11-26 10:14
@SinZ163 If I submit my addon to workshop, the LocalStorage library can runing? Where it saved the file?

**Comment by SinZ163** [comment] 2016-11-26 11:46
it saves to disk, `SteamLibrary/SteamApps/common/dota 2 beta/game/dota/scripts/moddota_storage/live/filename.kv` or more specifically, `WRITABLE_GAME_PATH/scripts/moddota_storage/live/filename.kv`

**Comment by SinZ163** [comment] 2016-12-29 10:48
Now being tracked in #53

**Closed by SinZ163** 2016-12-29 10:48 UTC
Labels: Feature request, Panorama
